name: Headless smoke tests

on:
  push:
  pull_request:

jobs:
  headless-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy vtk pydicom
      - name: Run headless smoke scenarios
        run: python tools/headless_smoke.py
